apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nginx-web"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: "nginx-web"
  template:
    metadata:
      labels:
        app: "nginx-web"
    spec:
      containers:
      - image: nginx:1.14.2
        name: "nginx-web-con"
        ports:
        - containerPort: 80
